### PR TITLE
Partially import melody project into core

### PR DESCRIPTION
**Pull request by zackad**
Related: GH-26, GH-32

This patch contains [trivago/melody](https://github.com/trivago/melody) that has been stripped down using `git-filter-repo`. This is an attempt to retain git history before applying GH-32.

### CODE REVIEW

**Comment by zackad** [comment]
Seems like #32 copying content from `packages/melody-*/src` into `src/melody/melody-*/` directly. We need to skip `src` directory from filtered repo.

**Comment by zackad** [comment]
need to re-import with fixed path to adhere #32 file structure.

__Script to filter melody project__
```shell
#!/usr/bin/env sh

# `melody-repo` is the original melody repository
# `target-repo` is git repo where the filtered will be placed
git filter-repo --source melody-repo --target target-repo \
	--path packages/melody-code-frame/src \
	--path packages/melody-extension-core/src \
	--path packages/melody-parser/src \
	--path packages/melody-types/src \
	--path packages/melody-traverse/src \
	--path-rename packages/melody-code-frame/src:src/melody/melody-code-frame \
	--path-rename packages/melody-extension-core/src:src/melody/melody-extension-core \
	--path-rename packages/melody-parser/src:src/melody/melody-parser \
	--path-rename packages/melody-traverse/src:src/melody/melody-traverse \
	--path-rename packages/melody-types/src:src/melody/melody-types
```

**Comment by rellafella** [comment]
obviously going to fail the tests due to all the Typescript within these files, but this looks like a successful merge!

**Comment by zackad** [comment]
Your PR on #32 has fixed this problem. Need to rebase with `--strategy-option=theirs` flag.

**Pull request merged**
